name: Manual trigger dependabot.yml
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: trigger dependabot refresh
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/dependabot/updates \
            -f package-ecosystem='maven' \
            -f directory='/' \
            -f target-branch='master'

        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
